### ISSUE TITLE
Tests for Microphone show warning message for device Pi 

### ISSUE THREAD

**Issue by cvranjani** [webrtc/testrtc#163]
1. Browse to https://test.webrtc.org/ 
2. Click Allow in the getUserMedia prompt
3. Click Start
4. Observe that tests for Microphone -> Audio Capture show warning sign with following details:
   " [ OK ] Audio track created using device=Default (pick up everything)
   [ INFO ] Channel 0 levels: 0.0 dB (peak), -0.7 dB (RMS)
   [ WARN ] Clipping detected! Microphone input level is high. Decrease input volume or move away from the microphone.
   [ INFO ] Channel 1 levels: -1.6 dB (peak), -8.1 dB (RMS)
   [ OK ] Active audio input channels: 2
   [ INFO ] Stereo microphone detected."

Expected results:
Tests for Microphone should pass successfully without any warnings or errors

Actual results:
Tests for Microphone should shows warning

Note:
1. Observed this issue on both M47 and M48 release on device Pi. Please find corresponding logs attached.
[M47_testrtc-2015-11-24T22-26-41.899Z.txt](https://github.com/webrtc/testrtc/files/43359/M47_testrtc-2015-11-24T22-26-41.899Z.txt)
[M48_testrtc-2015-11-24T22-42-02.447Z.txt](https://github.com/webrtc/testrtc/files/43360/M48_testrtc-2015-11-24T22-42-02.447Z.txt)
2. Audio and video during apprtc calls and hangouts is working fine on device Pi

**Comment by tednakamura** [comment]
I asked cvranjani@ to file this because audio captured from the device's mic sounds fine, but the clipping warning consistently fires in testrtc, even when she's not speaking or otherwise near the microphone. 

Is the large variation between the peak of channel 0 and the peak of channel 1 indicative of a hardware issue?

**Comment by KaptenJansson** [comment]
It could be. Keep in mind that the AGC is disabled in this test, in fact all audio processing is turned off due to wanting the raw audio in order to detect if a stereo mic and evaluate the Mic with as little interference as possible. Typically when the AGC is enabled, it will compensate for most cases where the gain is really high (you can still hear that the voice is very flat if the Mic gain is really high).

@fsolenberg do you have any additional input WRT to Ted's comment and this issue?

**Comment by KaptenJansson** [comment]
Closing due to age.
