### ISSUE TITLE
Reflexive Connectivity Problems

### ISSUE THREAD

**Issue by CraneUp** [webrtc/testrtc#176]
Hello I have great hopes in WebRTC but have difficulty testing the STUN. 

I've asked 15 friends in the region of Montreal, Quebec, Canada to test the https://test.webrtc.org/ tool and most of them, 12 out of 15 had an issue with reflexive connectivity. 

I'm not sure if I'm missing something but would that mean that unless people on both sides of the call have no problem with reflexive connectivity, we would not use STUN for the call?

I'm worried because that would mean in my area, almost all calls would have to go through TURN. 

Please help me because around the web I see 86% or 92% of all calls are supposed to go though STUN and I feel confused. 

Thank you!

**Comment by KaptenJansson** [comment]
Hi,

It could also just be that they are having issues connecting to the stun server for some other reason. You can use your own stun server to see if it makes a difference.

Open the hot dog menu to the right of the bug icon and fill in your own stun server (you can also do the same for turn).

Also, ask your friends what kind of networks they are using, if they are using some form of restricted networks or are behind a symmetric NAT, turn might be their only option.

**Comment by CraneUp** [comment]
Hello @KaptenJansson,

We have tried with a couple public STUN servers and always get the same results. We obtain the same results of almost always using the TURN when using our private servers from Xirsys. 

Most of my friends are with ISP Videotron or Bell for home use. 

What we have found out at our office is that by changing our TP-Link router to a new D-Link router, we can now use STUN from here. 

Again, do you see any reasons why we are still far from using mostly STUN ?

Thanks!

**Comment by KaptenJansson** [comment]
If your firewall/router is doing symmetric NAT or something along those lines it would prevent you from doing STUN. When you swapped out the routers, did you note the firewall/nat config on the router? 

Another great tool for trying out STUN/TURN servers is https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/. You should see reflexive candidates if able to connect to STUN server.

**Comment by CraneUp** [comment]
Hello @KaptenJansson,

Thank you for this response, I did note the config on the router. I've put the print screens online here: http://imgur.com/a/klzvZ

I also guess my router prevented the STUN in some way but I am still trying to investigate why it's common to have issues with STUN.

Also, thank you very much for the tool, I see start playing with it today.

**Comment by KaptenJansson** [comment]
What happens if you disable SPI on the TP-link router, does STUN work then?

**Comment by CraneUp** [comment]
Good question, 

I just tried and here's the result: http://imgur.com/dJSKJrL

Seems like the problem is elsewhere...

**Comment by KaptenJansson** [comment]
Did you try https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ using different turn/stun servers?

**Comment by KaptenJansson** [comment]
Ping?

**Comment by shacharz** [comment]
The reflexive connectivity test failed on an environment where I know for a fact is able to connect via stun

**Comment by KaptenJansson** [comment]
Do you get reflexive candidates from the default stun server on https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ ?

**Comment by shacharz** [comment]
![image](https://cloud.githubusercontent.com/assets/1267834/17515527/aaeec172-5e41-11e6-8520-2545fdf9f76d.png)

**Comment by KaptenJansson** [comment]
@shacharz do you see an error or warning for the reflexive test? An error means srflx candidates were not received while a warning means they were received but a connection could not be established.

**Comment by shacharz** [comment]
Warning:
![image](https://cloud.githubusercontent.com/assets/1267834/17560857/4a90d13a-5f2c-11e6-9988-e022cade78c4.png)

@KaptenJansson Where does it try to connect to?

**Comment by KaptenJansson** [comment]
Click on it and it will expand and show you the result. It tries to setup a data channel and connect to itself using the reflexive candidate. If this times out, then it's not reachable. This could be a network configuration factor, i.e. this might be blocked by your firewall.

**Comment by mcchin** [comment]
I got the same issue, and my issue is explained here
http://stackoverflow.com/questions/34611387/i-couldnt-establish-ice-connection-between-two-clients-in-same-lan-using-srvflx

not sure if your scenario is the same with mine

**Comment by shacharz** [comment]
@mcchin 
It can happen even though the same client (same device/network) is using reflexive candidates to connect to another client (not in the same LAN) ?

**Comment by KaptenJansson** [comment]
If relay candidates work in the same scenario, then yes, something in your network or the other client's network is preventing server reflexive candidates from working. Usually a NAT restriction.

**Comment by shacharz** [comment]
> If relay candidates work in the same scenario, then yes, something in your network or the other client's network is preventing server reflexive candidates from working. Usually a NAT restriction.

My bad I'll rephrase:
client1 is able to connect to client2 using reflexive candidates only
client1 is not passing the reflexive connectivity test

Is that a scenario which is possible from what @mcchin referred to or otherwise?

**Comment by KaptenJansson** [comment]
Then there could be something specific to how we setup the connection, i.e. your network might not allow the same machine to talk to itself using an external IP.

**Comment by geniusofthecrowd** [comment]
We have never seen the Reflexive test pass within our network despite having multiple STUN/TURN servers.

**Comment by sessionwire** [comment]
Was going to try this to trouble shoot client connections but the test is showing Reflexive connectivity failing and Relay connectivity succeeding from my location even though we connect using STUN only with our app and do so daily. We have no TURN server specified for our application and we are able to successfully connect via STUN. If STUN is not available our app fails to connect.

**Comment by KaptenJansson** [comment]
Have you entered the address of your own stun server in the test.webrtc.org settings before you ran the test? If you don't, it will use Google turn servers.

Reflexive quite often fails in corporate networks since they typical have symmetrical NAT or other restrictions preventing them from working.

**Comment by AxelDelmas** [comment]
> client1 is able to connect to client2 using reflexive candidates only
> client1 is not passing the reflexive connectivity test

I have the exact same issue here. I'm able to connect with other clients using only STUN on a variety of different networks, but somehow I don't pass the reflexive connectivity test

**Comment by KaptenJansson** [comment]
Have you used the same stun server for the tests?

**Comment by AxelDelmas** [comment]
Just retried with setting the stun server to the one we use, I have the same results.
Anyways, I'm able to get a srflx candidate. Just not able to connect:

 INFO ] Gathered candidate of Type: srflx Protocol: udp Address: xxx.xxx.xxx.xxx
[ WARN ] Could not connect using reflexive candidates, likely due to the network environment/configuration.

**Comment by KaptenJansson** [comment]
Hmm strange, and it works fine your client? Can you describe how your client connects? Trying to figure out why it wouldn't work in test.webrtc.org.

**Comment by bschmitlin** [comment]
+1 both Google and our own STUN servers fail, from multiple locations (private DSL and fiber with no firewall/NAT whatsoever) where we use STUN successfully daily. I'll take a look at the test.webrtc.org code to see if there is anything different from what we do in our app but it does look like a bug.

**Comment by KaptenJansson** [comment]
Ok will take a look soonish.

**Comment by octavn** [comment]
I am facing a similar issue where https://test.webrtc.org/ is 

1. finding reflexive ICE candidates 
2. but reporting "Could not connect using reflexive candidates, likely due to the network environment/configuration."

![screenshot from 2017-04-13 11 36 42](https://cloud.githubusercontent.com/assets/6663020/24997072/f16e1076-203d-11e7-9c8e-695f529b48b7.png)

while I can connect to Kurento using a `serverreflexive` candidate and stream video to the media server:

![screenshot from 2017-04-13 11 41 14](https://cloud.githubusercontent.com/assets/6663020/24997183/62d1035e-203e-11e7-9122-6258594bcb70.png)

**Comment by octavn** [comment]
Quick question:

Is having (reflexive) ICE candidates a guarantee that a connection can be established with the other person considering there's no limitation on the other side?

**Comment by KaptenJansson** [comment]
Closing due to age.

**Comment by bschmitlin** [comment]
I'm confused why this was closed, since this seems like a systematic non-trivial bug with the current https://test.webrtc.org/ that reflects negatively on the entire WebRTC community. Here is what it displays currently:
![image](https://user-images.githubusercontent.com/11586968/40713329-f974562a-63ff-11e8-938b-5900fd7368f3.png)

**Comment by InstantAli3n** [comment]
@KaptenJansson "Closed due to age" seems like an excuse to ignore the issue. I have not been able to get a passing result with any configuration or location.

**Comment by Spongman** [comment]
> Closing due to age.

hooray, i love the way these old bugs just retire and fix themselves!

**Comment by maxpavlov** [comment]
> > Closing due to age.
> 
> hooray, i love the way these old bugs just retire and fix themselves!

Its just this one wasn't fixed and the test tool is just wrong 100% of time =)

**Comment by nucleare** [comment]
I'm also encountering this error when utilizing the test page to troubleshoot issues with the Discord Desktop App failing to connect to voice chat. Oddly enough, if I use Discord in a browser, voice connection has no issues. I know that it is a firewall related issue because if I deactivate my firewall the Desktop App has no issues connecting to voice chat. However, even though Discord is whitelisted, I am uncertain of why this occurs and encounter the same results when running https://test.webrtc.org
I can't help but wonder if by chance, it is a windows service or process that is being blocked by the firewall that the app might utilize and not have permissions for as opposed to Google Chrome.

Side note: how are we still posting if this is closed?

**Comment by YaguraStation** [comment]
@nucleare Not a Windows-specific problem, also observable with Linux.

**Comment by nucleare** [comment]
@YaguraStation I forgot to mention though that I experienced the aforementioned issues on Windows 7 Ultimate. However, I have a dual-boot system with Windows 10 Pro on another drive and when I boot up with Windows 10 Pro on the same system (connecting to the same router with the same NAT settings and imported firewall settings) and run the Discord app, it connects to voice chat with no issues at all. 

Furthermore, after researching a bit more, I discovered that when establishing a websocket connection to Discord from a browser, the RPC origins are usually in the scheme form of http or https and because Chrome can connect via server reflexive candidates, a connection is established without issue. Yet it further complicates an explanation, from my lack of knowledge of course, how Windows 10 Pro handles the signaling differently to allow use of STUN/TURN to get past the firewall. But alas, I digress.

**Comment by felix91gr** [comment]
Hi. A friend of mine usually has problems using jitsi, so I asked her to run this test and see if it dropped some clues as to why.

Running the test in Chrome, under Windows, she gets this exact result.

But by reading the conversation I'm not sure if it's an actual failing of the setup, or if it's the test itself that's doing something wrong. Has anyone figured out what's going on yet?

**Comment by nucleare** [comment]
There's a lot of inconsistent data from this thread alone and testimonies across varying platforms make it difficult to find any correlations or consistencies. Perhaps we're dealing with varying issues that have resulting similar side effects? But ultimately, unfortunately it does not seem so. @felix91gr

**Comment by felix91gr** [comment]
Oh no ;_;

That really sucks because so far this is the only (privacy-preserving) stuff we've come up with that has allowed our group to have video calls to keep in touch.

At least Mumble exists. We can still talk to each other for now with no video.

Thanks, @nucleare. Take care 🌷

**Comment by omgbox** [comment]
issue might be with your isp, it is  probably using IPV6 with chrome using its own dns which are always ipv6 

my old isp, had only ipv4, with Carrier-grade NAT (CGN or CGNAT), also known as large-scale NAT (LSN), webrtc worked until i moved to new isp with ipv6 default.

**Comment by nucleare** [comment]
I was able to resolve my issue which had similar side effects and gave error warnings like those mentioned in this thread however, in my case, I always knew that if I disabled my firewall, I would have no connection issues but of course, I can't afford to leave my firewall indefinitely to resolve the issue. 
In my particular case,  the Discord app was what lead me to look into reflexive connectivity problems and as it turns out, it my firewall rules were not processing the environment variables properly. So, by changing the path from using the automatically inputted %USERPROFILE% path with the typical path C:\User\Username\* etc. I no longer had issues. Somewhat different than the discussions here but hopefully it might trigger some ideas.

**Comment by mar28131** [comment]
So im getting that Could not connect using reflexive candidates, likely due to the network environment/configuration message. I try to do calls thru a webpage but they will all cut off at 20 seconds . Dont know if there is something that is not set up correctly on my modem or my router. can anyone help please?

**Comment by nucleare** [comment]
> So im getting that Could not connect using reflexive candidates, likely due to the network environment/configuration message. I try to do calls thru a webpage but they will all cut off at 20 seconds . Dont know if there is something that is not set up correctly on my modem or my router. can anyone help please?

It would be more beneficial for you to start a new thread with your issue if it is in relation to issues with your use of https://test.webrtc.org/ **as this thread has been closed**. However, your question is a bit vague and with a newer account on GitHub, I'm worried you may not be able to find the help you are looking for as it's difficult to surmise whether your issue relates to the site itself and its use based on the information provided.

However, if you are referring to calls made using https://test.webrtc.org/ (which I would assume otherwise after you mentioned using a webpage and apologize _if my mentioning of Discord in a previous post causes confusion_) then for the purpose of using WebRTC, you may also want to try testing making calls to your TURN/STUN server using https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ to test connection issues there. Otherwise, have you entered the address of your own stun server in the test.webrtc.org settings before you ran the test? If you don't, it will use Google turn servers. If you're on a corporate network, you'll get the reflexive candidates failure because more often than not they have symmetrical NAT and/or other restrictions preventing them from working.

In the broad scope of things, if your calls are being cut off after 20 seconds, it sounds as if you're initially able to connect but the connection is aborted after 20 seconds which could relate to a number of things. Again, if you're having issues with a particular app that directed you to use https://test.webrtc.org/ in an attempt to determine what the underlying issue is (and "making calls" refers to voice communication and not using the word "call" in the programming sense, then I would suggest checking your firewall setting and allow UDP connections to pass through port 3478 and then run the WebRTC test again. If it succeeds then your firewall is preventing the connection with whatever app it was you were trying to use to make voice calls. If it still fails, then it will be a network issue which would need more information to help troubleshoot, but again, it would serve to benefit you more by finding the appropriate support forum.
