### ISSUE TITLE
force iframe-apprtc call to run on vp8

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#189]
**Browsers and versions affected**
M50 dev, M49 Stable 

**Description**
When I force an iframe-apprtc call to run on vp8, the codec sent is vp9

**Steps to reproduce**
1. Run https://test.webrtc.org/manual/iframe-apprtc/?vsc=vp8 in one machine and https://appr.tc/ in another
2. Observe the codec on both ends, via chrome://webrtc-internals (ssrc_<>_send stats) or press "i" in the apprtc call window

**Expected results**
The codec on the iframe-apprtc call should be vp8

**Actual results**
On both ends, I see the codec as vp9.

**Comment by KaptenJansson** [comment]
This is due to setting VP9 in the answer in AppRTC, the 2nd to join the call will therefore always depict which codec is used (if supported by both clients).

Hence this is not a bug, just that it's harder to join an existing call with an iframe unless you modify the page (i.e. add the room name to the iframe url link).

To conclude, this is not an bug related to iframes or apprtc.
