### ISSUE TITLE
Uncaught ReferenceError while trying to share a browser window

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/testrtc#196]
**Browsers and versions affected**
M51 Canary 51.0.2699.0

**Description**
I did a random search for something and there was a pop-up browser window (like an ad) in the background. While attempting to share that window in https://test.webrtc.org/manual/peer2peer/, I saw an Uncaught Reference Error in the JS console.

Uncaught ReferenceError: webrtcDetectedBrowser is not defined(anonymous function) @ main.js:414

**Steps to reproduce**
Pre-condition: Do a random search and have an ad pop up in the background. 
1. Open https://test.webrtc.org/manual/peer2peer/
2. Click on Screen capture and select the ad

**Actual results**
Uncaught ReferenceError seen while trying to share a pop-up browser window

Screenshots attached.

![screen shot 2016-04-04 at 11 52 19 am](https://cloud.githubusercontent.com/assets/14947786/14259614/92ea4608-fa5c-11e5-8ae6-3284c4c9f750.png)

![screen shot 2016-04-04 at 11 58 30 am](https://cloud.githubusercontent.com/assets/14947786/14259615/92eadf5a-fa5c-11e5-8817-766380832cf4.png)

**Comment by srnarayanan** [comment]
@KaptenJansson This happens even if I attempt to share the Entire screen / peer2peer page

**Comment by cvranjani** [comment]
This issue is also observed on CrOS with M51 51.0.2699.0 /8150.0.0 dev. 

Clicking on "Screen capture" in  https://test.webrtc.org/manual/peer2peer/ page displayed windows for each tab opened along with other available windows. When any of the windows are selected for screensharing, local preview did not share the selected window screen and JS logs show "Uncaught ReferenceError: webrtcDetectedBrowser is not defined(anonymous function) @ main.js:414"

**Comment by srnarayanan** [comment]
@KaptenJansson - I still see the webrtcDetectedBrowser JS error in today's M51 Canary.

**Comment by KaptenJansson** [comment]
Sorry did not push the new release, it's now pushed, please try again.

**Comment by srnarayanan** [comment]
looks good now, thanks!
