### ISSUE TITLE
Use of getStats api in the test break FF

### ISSUE THREAD

**Issue by ziaius** [webrtc/testrtc#74]
![test webrtc org](https://cloud.githubusercontent.com/assets/1709025/7180724/0dc41fba-e44d-11e4-9a8f-c9e5c162f1df.PNG)
Old laptop of mine: Latitidue e6400
during test I was connected to vpn network (openvpn)

TypeError: Argument 1 of mozRTCPeerConnection.getStats does not implement interface MediaStreamTrack.

had no problems with Canary
hope it's useful

**Comment by KaptenJansson** [comment]
Thanks for reporting this issue! 

Could you also attach the report link generated when you upload bug report via the bug button to the left of the start button?

**Comment by andresusanopinto** [comment]
It appears the tests are written against an getStats api supported by chrome and not by firefox.. will have a look tomorrow to unify that.

**Comment by ziaius** [comment]
Can not reproduce the very same bug. It's not consistent when repeating the same test but it works

**Comment by KaptenJansson** [comment]
The issue remains but we added a workaround for now.

**Comment by jgsacris** [comment]
Could you please comment on the workaround. The bandwidth tests are still breaking on Firefox and the call to getStats method still calls the old version of this method in the adapter. If I understand the code correctly, the new getStats method requires that you pass null as first argument of the function so that it works on Firefox. Unfortunately this method doesn't consolidate the different parameters delivered on the report and some parameters used on testrtc, namely googFrameWidthSent and googFrameHeightSent doesn't seem to have corresponding values on Firefox.   Please consider if it would be possible/useful to replace this values with some information that is available across browsers like for example the frame rate.
